version: 2.1
orbs:
    gh: circleci/github-cli@1.0.3
jobs:
    build:
        docker:
            -   image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      yarn install --frozen-lockfile
            - save_cache:
                  name: Save Cache
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
            - run:
                  name: Prettier Check
                  command: yarn prettier:check
            - run:
                  name: Build
                  command: yarn build
            - run:
                  name: Verify Artifacts
                  command: yarn test
            -   persist_to_workspace:
                    root: .
                    paths:
                        - dist

    publish:
        docker:
            -   image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            -   attach_workspace:
                    at: .
            -   run:
                    name: Authenticate with registry
                    command: |
                        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
                        echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            -   run:
                    name: Publish @brightlayer-ui/react-native-themes
                    command:  |
                        yarn publish:package -b $CIRCLE_BRANCH

    tag:
        docker:
            -   image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - gh/setup
            -   attach_workspace:
                    at: .
            -   run:
                    name: Tag @brightlayer-ui/react-native-themes
                    command: |
                        yarn tag:package -b $CIRCLE_BRANCH -s -blui-react-native-themes

workflows:
    version: 2
    themes:
        jobs:
            - build
            - publish:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - master
                              - dev
            - tag:
                  requires:
                      - publish
                  filters:
                      branches:
                          only:
                              - master
